name: gottani_mobile
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data Structures
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Development
  logger: ^2.4.0

  # Navigation
  auto_route: ^9.2.2

  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  supabase_flutter: ^2.8.0

  # OS Integrations
  share_plus: ^10.1.1
  url_launcher: ^6.3.1

  # Persistence
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

  # Riverpod
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod: ^2.6.1

  # UI
  cupertino_icons: ^1.0.6
  fl_chart: ^0.69.0
  gap: ^3.0.1
  transparent_image: ^2.0.1
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.10.0

  # Utilities
  collection: ^1.18.0
  uuid: ^4.5.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Analyzer
  custom_lint: ^0.6.8
  flutter_hooks_lint: ^1.2.1
  flutter_lints: ^5.0.0
  pedantic_mono: ^1.29.0

  # Data Structures
  freezed: ^2.5.7
  json_serializable: ^6.8.0

  # Generator Basis
  build_runner: ^2.4.13

  # Navigation
  auto_route_generator: ^9.0.0

  # Networking
  retrofit_generator: ^9.1.4

  # Tests
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
